# DeepPresenter 配置文件
research_agent:
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  model: "glm-4.7"
  api_key: "30badabb44864d0f9c7b114cd9a7fc9e.WX1mxvPZvDIuNOWq"
  allow_reflection: false

design_agent:
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  model: "glm-4.6v"
  api_key: "30badabb44864d0f9c7b114cd9a7fc9e.WX1mxvPZvDIuNOWq"
  is_multimodal: true
  use_qwen_tool_calling: false
  allow_reflection: true

ppt_agent:
  base_url: "https://api.siliconflow.cn/v1"
  model: "deepseek-ai/DeepSeek-R1"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"

long_context_model:
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  model: "glm-4.7"
  api_key: "30badabb44864d0f9c7b114cd9a7fc9e.WX1mxvPZvDIuNOWq"

vision_model:
  base_url: "https://api.siliconflow.cn/v1"
  model: "glm-4.6v"
  api_key: "59285983720a4fd3ad6aa0154158a64b.CVAlPbkAzm2UIgRT"
  is_multimodal: true

t2i_model:
  base_url: "https://api.siliconflow.cn/v1"
  model: "Kwai-Kolors/Kolors"
  api_key: "sk-yjommmmaewxwvxlwmclgertdctmdpyjzpfgeqxswjlndenhy"
  sampling_parameters:
    response_format: "b64_json"
    extra_body: { "watermark": False }
