# DeepPresenter 配置文件
research_agent:
  base_url: "https://api.siliconflow.cn/v1"
  model: "Pro/deepseek-ai/DeepSeek-V3.2"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"

design_agent:
  base_url: "http://192.168.50.9:18002/v1"
  model: "Qwen/Qwen3-Omni-30B-A3B-Instruct"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"
  soft_response_parsing: true
  is_multimodal: true
  sampling_params:
    max_tokens: 8196

ppt_agent:
  base_url: "https://api.siliconflow.cn/v1"
  model: "deepseek-ai/DeepSeek-R1"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"

long_context_model:
  base_url: "http://192.168.50.9:18002/v1"
  model: "Qwen/Qwen3-30B-A3B-Instruct-2507"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"

vision_model:
  base_url: "https://api.siliconflow.cn/v1"
  model: "Qwen/Qwen2.5-VL-32B-Instruct"
  api_key: "sk-cjcigurbfqpfuifbqnsubiafjwxmmnwlxrjmhjpmwbxrritq"

t2i_model:
  base_url: "https://api.siliconflow.cn/v1"
  model: "Kwai-Kolors/Kolors"
  api_key: "sk-yjommmmaewxwvxlwmclgertdctmdpyjzpfgeqxswjlndenhy"
  sampling_parameters:
    response_format: "b64_json"
    extra_body: { "watermark": False }
